### ISSUE TITLE
netflix decompile

### ISSUE THREAD

**Issue by lukeee1337** [REAndroid/APKEditor#107]
Describe the bug
After decompile and recompile app crash after few sec after run

To Reproduce

Used version '1.3.8'
Operating system 'Windows 11 23H2'
Command
java -jar H:\Temp\APKEditor-1.3.8.jar  d -i "H:\Temp\netflix.apk
java -jar H:\Temp\APKEditor-1.3.8.jar  b -i "H:\Temp\netflix"

**Comment by REAndroid** [comment]
Can't help without:

- Sample apk
- Crash logcat/stack trace
