### ISSUE TITLE
Using protect feature breaks the apk file!

### ISSUE THREAD

**Issue by GoRaN9O** [REAndroid/APKEditor#11]
Hi, 

I used this tool to decompile my own old application that removed from play store because my older account was suspended :( 

The hacking tools are works great like ( decomile , rebuild , refactor ) but when i use new feature Protect APK file it build the apk but you can't use it like a normal apk file I think that because the protected file is not signed and there is no way to sign it with any signer tool.

The apk file that i used is this [Kurdish Keyboard](https://apkpure.com/kurdish-keyboard-%D8%AA%DB%95%D8%AE%D8%AA%DB%95%DA%A9%D9%84%DB%8C%D9%84%DB%8C-%D9%83%D9%88%D8%B1%D8%AF%DB%8C/com.gorankeyboard.language.kurdi)  file I created my own keyboard for my language and layouts I used open source project [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard)

**Comment by REAndroid** [comment]
What signing tool do you used ?
Use ``` apksigner.jar ``` which is found under android sdk  ``` build-tools/x.x.x/lib/apksigner.jar ```

**Comment by REAndroid** [comment]
Your log tells your apk signed successfully, or i missed your question ?
Install your apk from command to see the error
 ``` adb install your_file.apk ```

**Comment by REAndroid** [comment]
You probably decompiled unprotected file or decompile without resources. I have tested with all known decompilers, please check again and create issue.

**Comment by REAndroid** [comment]
> ... but I used an russian Android app [APK Tool M](https://maximoff.su/apktool/?lang=en) Unfortunately with this app you can decompile and hack all sources of refactored & protected file.
> 
> 

First time seeing this app,  there are unlimited ways to make harder for decompiling but lets use one at a time. For now  check this [commit](https://github.com/REAndroid/APKEditor/commit/9b81a571c2880489204d7970d3792aeeb5408b5c) or you can use this update [APKEditor-1.1.7-UPDATE.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.1.7/APKEditor-1.1.7-UPDATE.jar) 

Thank you!

**Comment by REAndroid** [comment]
Glad to hear you enjoyed with this tool !  Finding issue is also great contribution for this project. 
Thank you for kind words !

**Comment by biden2020prez** [comment]
> > Glad to hear you enjoyed with this tool ! Finding issue is also great contribution for this project. Thank you for kind words !
> 
> Thank you very much you just saved my life now all my resources are protected and there no one can stole my codes and ideas GOD Bless you dear @REAndroid love and respect from Kurdistan.

Send me an  protected apk biden2020prez@gmail.com and i will try to unpack it
