### ISSUE TITLE
Can't install APK to FireTV after merging XAPK

### ISSUE THREAD

**Issue by martinbutt** [REAndroid/APKEditor#123]
Steps:
- Download armeabi-v7a XAPK, e.g. [Chrome](https://apkpure.net/google-chrome-fast-secure/com.android.chrome/download)
- Run merge command, e.g. `java -jar APKEditor-1.3.9.jar m -i chrome.xapk`
- Copy APK to FireTV
- Run APK and get the message "There was a problem parsing the package"

Notes:
- Install apps from unknown sources enabled

I'm not sure how to debug further.

**Comment by SubZero5** [comment]
The package is probably invalid imho...

**Comment by martinbutt** [comment]
I don't see any issues using `java -jar APKEditor-1.3.9.jar info -i chrome.apk`, or when using the APK Analyzer in Android Studio. How else should I check?

**Comment by martinbutt** [comment]
I did, using https://github.com/patrickfav/uber-apk-signer

**Comment by martinbutt** [comment]
Thanks for the tip! `Requires newer sdk version #26 (current version is #25)]`. I was able to go back to an older version and it worked.
