### ISSUE TITLE
[BUG] Mismatch in zip data descriptors

### ISSUE THREAD

**Issue by REAndroid** [REAndroid/APKEditor#124]
> Caused by: com.android.apksig.zip.ZipFormatException: Data Descriptor presence mismatch between Local File Header and Central Directory for entry AndroidManifest.xml. LFH: true, CD: false

The problem is with ZIP data descriptors, it's not a problem in the signature or AndroidManifest itself, but happens for all the files that are modified during merging I think (If you remove signature and preserve AndroidManifest.xml, same Data Descriptor presence mismatch exception thrown for resources.arsc).

I thought this is a mistake in apksig, because the APK will work fine if you remove the exception, but it's not (well it might still be unnecessary validation, but as Maximoff (developer of Apktool M) [noted](https://4pda.to/forum/index.php?showtopic=1002506&view=findpost&p=131701373), apksig does not throw this exception for merged APKs normally, only in ReVanced Manager/CLI, so he thinks it may be caused by something when patching). 

I don't know what exactly causes it or why, but I don't think this is a problem specific to APKEditor, because APKs merged by Apktool M and AntiSplit G2 have the same problem when patching with ReVanced. In AntiSplit M I simply removed the code from REAndroid which writes data descriptor, it works fine for merging, but I don't know if it would break other functions.

_Originally posted by @AbdurazaaqMohammed in https://github.com/REAndroid/APKEditor/issues/116#issuecomment-2322801093_

**Comment by brosssh** [comment]
I'm facing the same issue, Could a new version be released since a fix was made but not released? @REAndroid

**Comment by REAndroid** [comment]
@brosssh ARSCLib-1.3.7 Released now, also published on maven
