### ISSUE TITLE
META-INF folder is empty after merge

### ISSUE THREAD

**Issue by adtimizer** [REAndroid/APKEditor#13]
Hi,
after performing merge, in case there are files in the META-INF folder in the main APK and the other (such as config.en.apk,config.armeabi_v7a.apk) has an empty META-INF folder, the result is that the merged apk will have an empty (with folders only) META-INF folder.

**Comment by REAndroid** [comment]
Hello,

During merging , we modify apk so the orginal signing keys ``` *.SF, *.RSA, MANIFEST.MF ``` are invalid and should be cleared from META-INF but keep other files like ``` META-INF/services/* ```

Check [this commit](https://github.com/REAndroid/APKEditor/pull/2)  by @Kirlif

**Comment by REAndroid** [comment]
> Keeping META-INF is useful to install APK with original signature on a rooted device + disabled signature check using Core Patch module

Hello and warm welcome here 😃,
Maybe I should add option to let the user decide to keep signing keys, like ``` -keep-meta ```

**Comment by AndnixSH** [comment]
> > Keeping META-INF is useful to install APK with original signature on a rooted device + disabled signature check using Core Patch module
> 
> Hello and warm welcome here 😃, Maybe I should add option to let the user decide to keep signing keys, like `-keep-meta`

Yes, an option would always be great 👍

**Comment by REAndroid** [comment]
It is fixed now with [this](https://github.com/REAndroid/APKEditor/commit/1212e78adcbcd9f047f91f6e5dd23ab799828fd5), going to close it
