### ISSUE TITLE
Handle call_site_numbers incorrectly

### ISSUE THREAD

**Issue by zjw2017** [REAndroid/APKEditor#134]
**Describe the bug**
When I tried to decompile the Settings of Xiaomi HyperOS OS1.1.4.0.VNCNXM.BETA using APKEditor, I found that APKEditor couldn't handle call_site_numbers properly.

**To Reproduce**
1. Used version : APKEditor 1.4.1
2. Operating system : Android 15
3. Command : java -jar APKEditor.jar d -f -i /data/tmp/Settings.apk -o /data/tmp/settings

**Log/Stacktrace**
Null

**Used apk file**
[Settings of Xiaomi HyperOS OS1.1.4.0.VNCNXM.BETA](https://dumps.tadiphone.dev/dumps/xiaomi/houji/-/blob/88442e8f7531275cca8ca22ef775013f969e5644/system_ext/priv-app/Settings/Settings.apk)

**Additional context**
The abnormal method can be found at smali/classes3/com/android/settings/notification/modes/IconOptionsProvider$IconInfo.smali.

When using apktool, it's like this
```smali
.method public final equals(Ljava/lang/Object;)Z
    .registers 2

    .line 28
    invoke-custom {p0, p1}, call_site_0("equals", (Lcom/android/settings/notification/modes/IconOptionsProvider$IconInfo;Ljava/lang/Object;)Z, Lcom/android/settings/notification/modes/IconOptionsProvider$IconInfo;, "resId;description", instance-get@Lcom/android/settings/notification/modes/IconOptionsProvider$IconInfo;->resId:I, instance-get@Lcom/android/settings/notification/modes/IconOptionsProvider$IconInfo;->description:Ljava/lang/String;)@Ljava/lang/runtime/ObjectMethods;->bootstrap(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/TypeDescriptor;Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/invoke/MethodHandle;)Ljava/lang/Object;

    move-result p0

    return p0
.end method
```
When using APKEditor, it's like this
```smali
.method public final equals(Ljava/lang/Object;)Z
    .locals 0

    .line 28
    #disallowed odex opcode
    #iput-object-volatile p0, p2, Landroid/R$styleable;->SettingInjectorService:[I
    nop

    return-wide p0

    move-result p0

    return p0
.end method
```

I sincerely request developers to be aware of this issue and, if possible, provide me with a solution. Thank you very much!

**Comment by REAndroid** [comment]
Fixed with :https://github.com/REAndroid/APKEditor/commit/4a4b91bddfb025a3f19c2abda3adcc3188839d94

Thank you for reporting

**Comment by zjw2017** [comment]
I have downloaded and tested the new artifact and everything worked so perfectly. Thanks for fixing this Bug with such amazing speed. Thanks a lot!
