### ISSUE TITLE
After repacking,the number after call_site has changed.

### ISSUE THREAD

**Issue by zjw2017** [REAndroid/APKEditor#136]
**Describe the bug**

First of all, thank you for fixing issue #134  which successfully fixed the issue of call_site parsing errors. When I use it in Settings, everything works fine, but in services. jar, the number after call_site has changed, causing the physical keys to become invalid.

**To Reproduce**
1. Used version : APKEditor 4a4b91b(The latest Artifact for Fixing #134 )
2. Operating system : Android 15
3. Command : java -jar APKEditor.jar d -f -i /data/tmp/services.jar -o /data/tmp/services

**Log/Stacktrace**
Null

**Used apk file**
[services.jar of Xiaomi HyperOS OS1.1.4.0.VNCNXM.BETA](https://dumps.tadiphone.dev/dumps/xiaomi/houji/-/blob/88442e8f7531275cca8ca22ef775013f969e5644/system/system/framework/services.jar)

**Additional context**
Search call_site to get all problematic methods.

The normal code is like this
```smali
    invoke-custom {p0, p1}, call_site_0("equals", "Omit other code"
    invoke-custom {p0}, call_site_1("hashCode", "Omit other code"
    invoke-custom {p0}, call_site_2("toString", "Omit other code"
```
When using APKEditor to recompile, it becomes like this :
```smali
    invoke-custom {p0, p1}, call_site_3("equals", "Omit other code"
    invoke-custom {p0}, call_site_14("hashCode", "Omit other code"
    invoke-custom {p0}, call_site_5("toString", "Omit other code"
```

The number after call_site has changed :
0->3
1->14
2->5

Here are more details for this issue.
decompile :
![decompile ](https://github.com/user-attachments/assets/2f6a49bf-6712-48c4-bb44-480c87891eac)
recompile :
![recompile ](https://github.com/user-attachments/assets/635fabcc-b0bd-4b28-9276-024fe57882c3)

I sincerely request developers to be aware of this issue and, if possible, provide me with a solution. Thank you very much!

**Comment by REAndroid** [comment]
Check the last commit :https://github.com/REAndroid/APKEditor/commit/fd35f8649f0b51eee8a784e255801e7e4da0991f

**Comment by zjw2017** [comment]
It works fine! Thanks! Wish you a good day!
