### ISSUE TITLE
xapk convert to apk,and install ERROR

### ISSUE THREAD

**Issue by ComputerStudent00** [REAndroid/APKEditor#138]
i use the "java -jar APKEditor.jar m -i apk_files" to get apk.
then i install the apk in Lineage OS （Android 21）ERROR。
Remind me this is bad APK.
i install Android Simulator (Android 12) is right.

apk is too big ,i cannt upload.
thanks . please!

**Comment by ComputerStudent00** [comment]
https://1drv.ms/u/s!Ajyt6C6qaBo6llttwi3u6URV9bj0?e=Ut3jfv
https://1drv.ms/u/s!Ajyt6C6qaBo6llyKBMVls8FZfAUB?e=a4NZko
this is original xapk and Generated merged apk.

**Comment by REAndroid** [comment]
1. Did you sign your apk after merge ?
2. What is the error code if you tried to install from adb command ? `adb install file.apk`

**Comment by ComputerStudent00** [comment]
> 1. Did you sign your apk after merge ?
> 2. What is the error code if you tried to install from adb command ? `adb install file.apk`

OK， i will try it today.and i will tell you the result

**Comment by ComputerStudent00** [comment]
> 1. Did you sign your apk after merge ?
> 2. What is the error code if you tried to install from adb command ? `adb install file.apk`

how can i sign the apk?
i use adb install.
the ERROR information:
E:\Phone\platform-tools>adb install E:\Phone\soft\VPNProton_merged.apk
Performing Streamed Install
adb: failed to install E:\Phone\soft\VPNProton_merged.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl530976927.tmp/base.apk using APK Signature Scheme v3: SHA-256 digest of contents did not verify]

**Comment by REAndroid** [comment]
Search "How to sign apk"
Closing

**Comment by Un1Gfn** [comment]
quick and dirty apk sign snippet https://github.com/REAndroid/APKEditor/issues/8#issuecomment-3982411737
