### ISSUE TITLE
Call_Site is discontinuous

### ISSUE THREAD

**Issue by zjw2017** [REAndroid/APKEditor#139]
**Describe the bug**
From: https://bbs.binmt.cc/thread-140308-1-1.html

The author of MT Explorer said this is still not perfect enough(#136 ), it must exist in sequence with call_site_0 call_site_1、call_site_2..., Otherwise, if one is missing, the compilation will still be confused.

He found this because after modifying the code, MT's dex++compiles that file into a separate dex for caching, which leads to a situation where if a class only has call_Site_3 call_site_4、call_site_5, So after caching, it becomes 0, 1, 2, and finally merged into the main dex, it becomes chaotic.

**To Reproduce**
Null

**Log/Stacktrace**
Null

**Used apk file**
Null

**Additional context**
It seems that APKEditor also uses cache for unmodified dex, which may result in the same error. But currently, I haven't found such an apk or jar. This is just a suggestion. If I discover similar behavior, I will write down the steps to follow. thank you

**Comment by REAndroid** [comment]
@zjw2017 
The names `call_site_xx` is just a label, similar to like `:cond_1` (i.e not stored on dex) the last fix on #136 relies on number name number suffix, now corrected with proper sorting logic.

There was a big issue #136 in calculating out size:https://github.com/REAndroid/smali-lib/commit/255edcecc0b86645edb13b0a1cb25fdef231deb5 , am surprised it worked for you.

Check the last commit: https://github.com/REAndroid/APKEditor/commit/44fd18b92adcd59a94b1cefa0712d3c50894c863
