### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by bruskofgod** [REAndroid/APKEditor#15]
I am getting this error when running with the following commands

"java -jar APKEditor-1.1.7-UPDATE-3.jar d -i file.apk"

![image](https://user-images.githubusercontent.com/58754583/226269085-d08cc05d-d6ba-4ff3-b003-f7db872c8032.png)

**Comment by REAndroid** [comment]
Looks TypeBlock with null entry, please share the apk

**Comment by bruskofgod** [comment]
[7C148294A40FC93AE7068DA62F4079D209707CF69349E0A3544DE1D9AA379036.zip](https://github.com/REAndroid/APKEditor/files/11025821/7C148294A40FC93AE7068DA62F4079D209707CF69349E0A3544DE1D9AA379036.zip)

**Comment by REAndroid** [comment]
This apk has multiple issues with this tool:
- Original issue (Null pointer exception) on reading TypeBlock is [fixed](https://github.com/REAndroid/ARSCLib/commit/3e87435a1d56ac00837710fed697b30fa1dcfbc9)
- This apk has file entry under assets/* with a very long file name, I made temporary fix by just logging the error and continue decompile process.

You can build your own or get new update here: [APKEditor-1.1.7-UPDATE-4](https://github.com/REAndroid/APKEditor/releases/download/V1.1.7/APKEditor-1.1.7-UPDATE-4.jar)
