### ISSUE TITLE
Failed to install the merged apk [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

### ISSUE THREAD

**Issue by openarun** [REAndroid/APKEditor#18]
I tried to install a merged apk file using adb install.
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1926639033.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1926639033.tmp/base.apk: Attempt to get length of null array]

**Comment by REAndroid** [comment]
You need to sign your merged apk
