### ISSUE TITLE
1.1.9 

### ISSUE THREAD

**Issue by Quicker666** [REAndroid/APKEditor#19]
Its seem execute protect apk now looks very too clean, is it do it any protect on the resources like old version ?  Not very sure where the part resources protect

**Comment by Quicker666** [comment]
Somehow it also break my stuff after execute protect, imma use back the old version better

**Comment by REAndroid** [comment]
Yes I confirm this issue, until next release you can test with [APKEditor-1.1.9-UPDATE-1.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.1.9/APKEditor-1.1.9-UPDATE-1.jar)
