### ISSUE TITLE
Protectecd APK File Could NOT Upload to Play Store!

### ISSUE THREAD

**Issue by GoRaN909** [REAndroid/APKEditor#22]
Hi and thank you for this amazing tool it's very good and helpful to protect our content from reverse engineering or modding the two main feature `Refactor` and `Protect` are so great to protect APK file against any editor or modder but it have a small bug when you want to upload the protected file to play store you get some errors that app not compiled properly or it doesn't have meta data `com.android.vending.derived.apk.id` my apk file is already included that meta data and it's compiled without any errors and it's signed with same signature certificate I can install on my devices but I don't know what is the problem play store console doesn't let me upload it to release new protected version. 

Need some help please

Here is the screenshot: 

![Screenshot 2023-05-05 171213](https://user-images.githubusercontent.com/3160786/236484977-4c203a90-da7c-4563-bde8-3aa5d1b79eb7.png)

**Comment by REAndroid** [comment]
Most probably the parser on google is failed because of our protection on manifest. The solution is to protect files without manifest. Maybe I should add ```-skip-manifest```  ?

**Comment by GoRaN909** [comment]
> Most probably the parser on google is failed because of our protection on manifest. The solution is to protect files without manifest. Maybe I should add `-skip-manifest` ?

Yes you right the protecting/refactor is somehow changes the manifest that should not touch it becuase it can't be uploading to play store. Could you plesae fix that :)

**Comment by REAndroid** [comment]
You can skip AndroidManifest protection by using flag ```-skip-manifest```

```java -jar APKEditor.jar p -skip-manifest -i your_file.apk```

Check the latest update

**Comment by GoRaN909** [comment]
Okay bro thank you let me check it now wait please..

**Comment by GoRaN909** [comment]
> You can skip AndroidManifest protection by using flag `-skip-manifest`
> 
> `java -jar APKEditor.jar p -skip-manifest -i your_file.apk`
> 
> Check the latest update

I tested it's same warning like before this happens only when you `Protect` apk file it's okay with `Refactor` 

I used the [latest](https://github.com/REAndroid/APKEditor/releases/download/V1.2.0/APKEditor-1.2.0.jar) jar file on release page 

![Screenshot 2023-05-05 171213](https://user-images.githubusercontent.com/3160786/236581110-6aa41787-725e-4dd7-8980-bdecde1faad9.png)

**Comment by REAndroid** [comment]
My guess is the parser at playstore failed when it  tries to resolve references ( like app name, icon ...) from manifest, this references linked to resource.arsc  which is protected

**Comment by GoRaN909** [comment]
> My guess is the parser at playstore failed when it tries to resolve references ( like app name, icon ...) from manifest, this references linked to resource.arsc which is protected

So what things do I need to do to fix that problem in my app content?

**Comment by REAndroid** [comment]
I don't know may be use custom resources just like facebook which loads at runtime ??? BTW I am surprised play store still accepts ```.apk``` format

**Comment by GoRaN909** [comment]
> I don't know may be use custom resources just like facebook which loads at runtime ??? BTW I am surprised play store still accepts `.apk` format

No I doesn't used any facebook resources and my app is no need any permission to work only used this `<uses-permission android:name="android.permission.VIBRATE"/>` one to vibrate when user tap on keys!

And yeah play store is still support `.APK` format but it always advise you to use an `.AAB` app bundles to save storage and faster installation time on devices.

Anyways thanks for your work I like it so much the `Refactor` is maybe good enough for now.
