### ISSUE TITLE
Recompiled package has incorrect resources

### ISSUE THREAD

**Issue by okp2023** [REAndroid/APKEditor#25]
If you recompile some multiresources apk once, then recompile this result one more time you will get the different resources folders. Some files differs by order of lines. It's unimportant though uncomfortable to compare. But some files simply dissapeared. It is surely a bug. I used MX Player files: https://mx.j2inter.com/download

**Comment by REAndroid** [comment]
Some resource paths renamed to match resource entry name but the rename history is recorded on ```path-map.json``` during build all renamed files will be restored accordingly.
example:
```json
 {
  "name": "res/anim-v21/design_bottom_sheet_slide_in.xml",
  "alias": "res/anim/design_bottom_sheet_slide_in.xml"
 }
```

**Comment by okp2023** [comment]
Right now your update-03 cannot compile resources again.

**Comment by REAndroid** [comment]
next time focus on main issue
