### ISSUE TITLE
-keep-meta gives an error

### ISSUE THREAD

**Issue by adtimizer** [REAndroid/APKEditor#29]
when trying to run 
java -jar APKEditor-1.2.1.jar m -keep-meta -i com.kwai.bulldog/
i get the message  - Unknown option: -keep-meta

can anyone give a hint?

**Comment by REAndroid** [comment]
Flag ```-keep-meta``` is depreciated as of [83dc6f4](https://github.com/REAndroid/APKEditor/commit/83dc6f4c6b4e65bd9a37baecd9e95af29124e3cb) and the purpose is now default however if you want to remove META-INF use ```-clean-meta```

Run without args or with ```-h``` to see detail help/usage

**```java -jar APKEditor.jar m ```**
``` 
Merges split apk files from directory or XAPK, APKM, APKS ...
Options:
   -i         input path
   -o         output path
   -res-dir   sets resource files root dir name
              (eg. for obfuscation to move files from 'res/*' to 'r/*' or vice
              versa)
Flags:
   -f            force delete output path
   -clean-meta   cleans META-INF directory along with signature block

Example-1:
   java -jar APKEditor-1.2.1.jar m -i path/to/input -o path/to/out.apk
```
