### ISSUE TITLE
error when build apk. The application builds without errors, but when I install the application, the message Application is not installed

### ISSUE THREAD

**Issue by lamideag** [REAndroid/APKEditor#30]

**Comment by lamideag** [comment]
Everything works fine, but when signing an application, the application does not install on my phone. I tried a lot, but we did not succeed. Could you help me

**Comment by REAndroid** [comment]
I guess you confused "signing apk" and "restore signature block".

Read discussion #3

**Comment by lamideag** [comment]
> I guess you confused "signing apk" and "restore signature block".

Can you give me an example of signing an application. Please help me
