### ISSUE TITLE
Resource are corrupted after recompiling

### ISSUE THREAD

**Issue by okp2023** [REAndroid/APKEditor#33]
1. If you recompile an apk file in json-mode you get corrupted language files. It looks like that utf-8 is not supported. Just for your information: original resources.arsc is 19mB, the file after recompiling is 24mB. Feel the difference.
2. If you recompile an apk file in xml-mode you get some files corrupted. Thus if I put resources.arsc and res folder into original apk I get wrong scrollbar color.

**Comment by REAndroid** [comment]
Attach your apk

**Comment by REAndroid** [comment]
> 1. If you recompile an apk file in json-mode you get corrupted language files. It looks like that utf-8 is not supported. Just for your information: original resources.arsc is 19mB, the file after recompiling is 24mB. Feel the difference.

I decompiled-compiled your apk the file size is almost identical 19.1Mb. But file size doesn't matter, it could happen due to strings encoding or rearranging entry configs.

>2. If you recompile an apk file in xml-mode you get some files corrupted. 

Which files ?

> Thus if I put resources.arsc and res folder into original apk I get wrong scrollbar color.

Some resource paths maybe different , the two resources are identical but doesn't mean the same.

**Comment by okp2023** [comment]
![Screenshot_2023-06-01-09-04-46-93](https://github.com/REAndroid/APKEditor/assets/133634310/6b32e952-78d7-46ef-a3f5-9814d4f0af7c)
![Screenshot_2023-06-01-09-03-50-04](https://github.com/REAndroid/APKEditor/assets/133634310/2b628de6-c5a3-4e54-b844-15277db9adb4)

**Comment by okp2023** [comment]
First screenshot: original resources. The second one: xml recompilation.
![Screenshot_2023-06-01-10-18-06-69](https://github.com/REAndroid/APKEditor/assets/133634310/66e42543-d05d-4b0d-aa82-265c1fee01e3)
![Screenshot_2023-06-01-10-42-44-80](https://github.com/REAndroid/APKEditor/assets/133634310/a4d0c4e6-3716-4cc3-ad01-69b7679fcfeb)

**Comment by REAndroid** [comment]
> Are you kidding? Json mode: original file is 70582959 bytes. Recompiled one is 80497395 bytes. Original recources.arsc is 19082920 bytes, recompiled - 25630892. Right now I have recompiled the result of the first recompilation. Here you are: apk is 92593421 bytes, resources.arsc is 37724524 bytes. How can it be right if resources file grows every time?
JFYI, Apktool always gives the same resources independently the number of recompilations.

Here I am trying to help, but you are impolite.
Don't come here again!

**Comment by okp2023** [comment]
Impoliteness is when someone consider himself infallible. I twice wrote to you and both times you waveв off my words. I will go but it won't make your project to work correctly. Good luck.
