### ISSUE TITLE
Protected apk failed to intalled

### ISSUE THREAD

**Issue by jakanaka** [REAndroid/APKEditor#42]
**Describe the bug**
Protected apk failed to install. I've signed the zip with latest apk signer and apktool m and applied protected after.

**To Reproduce**
1. Used version 'V1.2.4'
2. Operating system 'windows'
3. Command 'java -jar APKEditor.jar p -i path/to/input.apk' and 'java -jar APKEditor.jar  p -skip-manifest -i path/to/input.apk'

**Log/Stacktrace**
```
00.044 I: [PROTECT] Loading apk ...
00.269 I: [PROTECT] Confusing AndroidManifest ...
00.295 I: [PROTECT] Protecting files ..
00.296 I: [PROTECT] Protecting files ..
00.324 I: [PROTECT]   Ignored: res/font/roboto_medium_numbers.ttf
00.329 I: [PROTECT] Protecting resource table ..
00.329 I: [PROTECT] METHOD-1 Protecting resource table ..
00.335 I: [PROTECT] METHOD-2 Protecting resource table ..
00.351 I: [PROTECT] Writing apk ...
00.365 I: [PROTECT] Buffering compress changed files ...
00.474 I: [PROTECT] Zip align ...
00.496 I: [PROTECT] Writing files: 1795
00.685 I: [PROTECT] Writing signature block ...
00.698 I: [PROTECT] Saved to: <name>
```

**Used apk file**
Attach/share your apk

**Additional context**
Android version: 11
RealmeUI

**Comment by REAndroid** [comment]
I can not reproduce your issue without apk. If you can not share your apk here, try find other apk.

**Comment by jakanaka** [comment]
> I can not reproduce your issue without apk. If you can not share your apk here, try find other apk.

https://4pda.to/forum/index.php?showtopic=885885&st=140#entry122933077

**Comment by REAndroid** [comment]
> > I can not reproduce your issue without apk. If you can not share your apk here, try find other apk.
> 
> https://4pda.to/forum/index.php?showtopic=885885&st=140#entry122933077


This is **forum** not apk file

**Comment by jakanaka** [comment]
> > > I can not reproduce your issue without apk. If you can not share your apk here, try find other apk.
> > 
> > 
> > https://4pda.to/forum/index.php?showtopic=885885&st=140#entry122933077
> 
> This is **forum** not apk file

● armeabi-v7a, arm64-v8a: (35.3 MB)
https://devuploads.com/acsbb9o2bi7f

Mirrors:
https://mega4upload.com/9fe2t1duu9kt
https://dropgalaxy.vip/q1gjuoghf6kv

**Comment by REAndroid** [comment]
> > This is **forum** not apk file
> 
> ● armeabi-v7a, arm64-v8a: (35.3 MB) https://devuploads.com/acsbb9o2bi7f
> 
> Mirrors: https://mega4upload.com/9fe2t1duu9kt https://dropgalaxy.vip/q1gjuoghf6kv

<img src="https://github.com/REAndroid/APKEditor/assets/94234159/a11052d1-8338-4433-8509-df956d2691d9" height="300"/>

## Again this is an AD not APK file
there are a ton of decent cloud service providers , idk why you choose me to suffer through clicks clacks

**Comment by jakanaka** [comment]
> > > This is **forum** not apk file
> > 
> > 
> > ● armeabi-v7a, arm64-v8a: (35.3 MB) https://devuploads.com/acsbb9o2bi7f
> > Mirrors: https://mega4upload.com/9fe2t1duu9kt https://dropgalaxy.vip/q1gjuoghf6kv
> 
> <img alt="" height="300" src="https://user-images.githubusercontent.com/94234159/250974729-a11052d1-8338-4433-8509-df956d2691d9.png">
> ## Again this is an AD not APK file
> There are a ton of decent cloud service providers , idk why you choose me to suffer through clicks clacks. You can refer other issues

here https://sendgb.com/Nn3h8fSOxqz

**Comment by REAndroid** [comment]
I tested your apk and I can not reproduce your issue.
What is your log from ``` adb install ```?

**Comment by Kirlif** [comment]
adb is quite terse here:
```
Performing Streamed Install
Success
```
@jakanaka, please to share the unprotected version of your file.
It will help to try to reproduce and to understand your issue.

**Comment by jakanaka** [comment]
Thank you for your replay. adb install showed that i had something wrong with my sign key. I signed the protected app and  it installed
