### ISSUE TITLE
APKEditor can't find layout component by resource id

### ISSUE THREAD

**Issue by naijun0403** [REAndroid/APKEditor#47]
**Describe the bug**
I modified the Smali code using APKEditor and rebuilt it. However, the built apk says that there is a problem with the resource or that the related resource cannot be found. I didn't touch any of the resources prior to the build, only smali code. However, when decompiling with jadx, the resource seems to exist.
(It's not a smali problem though, it works if you apply the same changes in apktool)

**To Reproduce**
1. Used version 1.2.5
2. Operating system macOS 13.4.1
3. Command `java -jar ~/APKEditor-1.2.5.jar d -i kakaotalk-10-2-8.apk -o kakaotalk`

**Log/Stacktrace**
>07-10 21:24:31.662 21956 21956 E AndroidRuntime: java.lang.NullPointerException: Missing required view with ID: com.kakao.talk.contenttab:id/back
07-10 21:24:31.662 21956 21956 E AndroidRuntime: 	at com.kakao.talk.contenttab.kakaoview.presentation.screen.main.a.onCreateView(KvMainFragment.kt:21)
07-10 21:24:31.662 21956 21956 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
07-10 21:24:31.662 21956 21956 E AndroidRuntime: 	at androidx.fragment.app.i0.e(FragmentStateManager.java:30)
07-10 21:24:31.662 21956 21956 E AndroidRuntime: 	at androidx.fragment.app.i0.j(FragmentStateManager.java:29)
07-10 21:24:31.662 21956 21956 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.E(FragmentManager.java:126)
07-10 21:24:31.662 21956 21956 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.l0(FragmentManager.java:9)
07-10 21:24:31.662 21956 21956 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.D(FragmentManager.java:5)
07-10 21:24:31.662 21956 21956 E AndroidRuntime: 	at androidx.fragment.app.a.i(BackStackRecord.java:2)

**Used apk file**
[Attach/share your apk](https://apkcombo.com/kakaotalk/com.kakao.talk/download/phone-10.2.8-apk)

**Additional context**
At this time, a simple change in Smali is just a bypass of forgery detection.

**Comment by REAndroid** [comment]
Good issue, fixed with [ffe5c87](https://github.com/REAndroid/APKEditor/commit/ffe5c87fd470c17dfca4515818ac40ee06927eaa)
NB: [APKEditor-1.2.5.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.5/APKEditor-1.2.5.jar) also updated

**Comment by naijun0403** [comment]
That's a nice fix! It works fine. However, there is a problem that some resources are not reflected as html tags and are displayed as plain text. However, the issue has been fixed, and I think it is a different issue, so I will close the issue.
