### ISSUE TITLE
APKEditor can't handle tags in string resources

### ISSUE THREAD

**Issue by naijun0403** [REAndroid/APKEditor#49]
**Describe the bug**
If you decompile with APKEditor and build again, tag processing, which was originally good, does not work.
Please refer to the picture for related information

![image](https://github.com/REAndroid/APKEditor/assets/101266316/4d66dce2-d7c6-4e2e-9552-bbe8d81b3a48)

**To Reproduce**
1. Used version 1.2.5
2. Operating system macOS 13.4.1
3. Command
> decompile: `java -jar ~/APKEditor-1.2.5.jar d -i kakaotalk.apk -o kakaotalk`
> compile: `java -jar ~/APKEditor-1.2.5.jar b -i kakaotalk -o kakaotalk.apk`

**Log/Stacktrace**
Nothing.

**Used apk file**
[Attach/share your apk](https://apkcombo.com/kakaotalk/com.kakao.talk/download/phone-10.2.8-apk)

**Additional context**
Related classes are the same as `xc.f`, and you can refer to the `label_multi_photo_guide resource`.

**Comment by REAndroid** [comment]
Check the latest update

**Comment by naijun0403** [comment]
It's working! thanks
