### ISSUE TITLE
Input XAPK path?

### ISSUE THREAD

**Issue by ghost** [REAndroid/APKEditor#6]
Can you support input XAPK path to automatically extract it and proceed the merging process? I'm lazy to extract it manually just to use the input path

**Comment by REAndroid** [comment]
XAPK , APKM ... are used by apk sharing sites and are not standard files. For example  XAPK uses Zip-3.0 compression which is not supported by native java(1.8) ```ZipInputStream```

**Comment by REAndroid** [comment]
I couldn't get good zip lib without compromising speed and memory. I am not even satisfied with performance of native java zip lib. Maybe i will do zip lib from scratch in the future :)

**Comment by REAndroid** [comment]
Now it supports [XAPK, APKM, APKS](https://github.com/REAndroid/APKEditor/commit/505d85c5c7f1e4ce88c4049dadf828f85f5fda8d)
