### ISSUE TITLE
ApplicationInfo.metaData very strange error

### ISSUE THREAD

**Issue by kiber-io** [REAndroid/APKEditor#65]
**Describe the bug**
The application has metadata specified in the application tag. In the original apk, you can get the value of the key `com.push server.android.serverparyid` with the `ApplicationInfo.metaData.getString` method. But after recompiling without making changes, this method starts returning null and only `ApplicationInfo.metaData.getInt` works. And I can't figure out why...

**To Reproduce**
1. Used version: 1.2.9
2. Operating system: WSL Ubuntu 22.04
3. Command: `java -jar apkeditor.jar d -i app.apk` & `java -jar apkeditor.jar b -i app_decompiled_xml`

The problem appears in the method `Lcom/edna/android/push_lite/repo/config/NetworkConfiguration;->initPrimaryServer(Landroid/os/Bundle;)V` at line `invoke-virtual {p1, v0}, Landroid/os/BaseBundle;->getString(Ljava/lang/String;)Ljava/lang/String;` (it returns null on recompiled apk)
The value itself is specified in the manifest: 
```xml
<application android:theme="@style/FaceliftTheme"
...
<meta-data android:name="com.pushserver.android.serverPrimaryId" android:value="@string/mfms_primary_id" />
...
</application>
```

**Used apk file**
Original apk: https://drive.google.com/file/d/1VGqz-vIoa70ESahvQTuIs0EqIq-vp2b1/view?usp=sharing

**Additional context**
I wrote a simple program that requests metadata from the application and shows the problematic key (the first line), and also outputs the entire contents of the Bundle: https://drive.google.com/file/d/14Xh4xnmDz5wcJx9a0v1TDp_ACw1WkCEi/view?usp=sharing
There you need to click on the FAB at the bottom to get the data. the original application must be installed accordingly
![изображение](https://github.com/REAndroid/APKEditor/assets/60169133/77145fc1-180d-42f9-8a0a-dd2103357dca)

**Comment by kiber-io** [comment]
so, I found out the reason a little more precisely.
if you decompile the original apk in json mode, then in the `resources.arsc.json` can see that the `mfms_primary_id` key has `value_type` = `STRING`.
and in the precompiled apk `value_type` is already `DEC`

**Comment by kiber-io** [comment]
yes, Google blocked the file, because it is signed with a test-key :))
I have uploaded a new file with custom sign: https://drive.google.com/file/d/1YeQ9epTdNFo3i5xpN9sdQc0Ejlo4jWDC/view?usp=sharing

**Comment by REAndroid** [comment]
> yes, Google blocked the file, because it is signed with a test-key :)) I have uploaded a new file with custom sign: https://drive.google.com/file/d/1YeQ9epTdNFo3i5xpN9sdQc0Ejlo4jWDC/view?usp=sharing

Same result

**Comment by kiber-io** [comment]
> > yes, Google blocked the file, because it is signed with a test-key :)) I have uploaded a new file with custom sign: https://drive.google.com/file/d/1YeQ9epTdNFo3i5xpN9sdQc0Ejlo4jWDC/view?usp=sharing
> 
> Same result. You can see it yourself by opening your link in private-mode browser

Tested, everything opens and gives download.
Let's try mega: https://mega.nz/file/Vlt10A4J#Nxe5_k65AafQSVMN98mFdhULLE_1iU6VLUmiEbQU1jE

**Comment by kiber-io** [comment]
yes, everything is fixed :)
do you just need a recompiled apk? if yes, then here: https://mega.nz/file/x4UAXbQZ#bA9ZTORlvWivzfWZ87gsLlh52JbGo6qikgo0NZP9Sqg

**Comment by REAndroid** [comment]
> yes, everything is fixed :) do you just need a recompiled apk? if yes, then here: https://mega.nz/file/x4UAXbQZ#bA9ZTORlvWivzfWZ87gsLlh52JbGo6qikgo0NZP9Sqg

The reason I asked you for re-compiled apk was to see the reaction of `google-drive`, I was guessing gdrive's software  report as a "virus" if it can't parse  AndroidManifest file.
