### ISSUE TITLE
APKEditor on Android ?!

### ISSUE THREAD

**Issue by 0frd** [REAndroid/APKEditor#71]
Any chance having APKEditor running on Android device ?

**Comment by kiber-io** [comment]
what prevents you from doing it now? it is completely written in Java

**Comment by REAndroid** [comment]
If you mean apk editor for android, yes there is a plan after dex project is completed.

**Comment by 0frd** [comment]
> If you mean apk editor for android, yes there is a plan after dex project is completed.

Good to know. Im cant access my pc for awhile thats why i asked. But im good for now, i just knew it can run on termux.
