### ISSUE TITLE
Add api support when decoding dex

### ISSUE THREAD

**Issue by Zelooooo** [REAndroid/APKEditor#79]
Some files will require api when decoding dex files

Thank you for a great tool.

**Comment by REAndroid** [comment]
dexlib2 will be depreciated and replaced by our builtin [dex](https://github.com/REAndroid/ARSCLib/tree/main/src/main/java/com/reandroid/dex) parser. Till this fully implemented, this feature along with others will be included on next version

**Comment by Zelooooo** [comment]
Thanks
