### ISSUE TITLE
Failed to install the apk after merged 

### ISSUE THREAD

**Issue by raoshaab** [REAndroid/APKEditor#8]
While trying to install the app via adb
```
01.778 I: [MERGE] Writing apk ...
05.458 [MERGE] Writing: total=35638710 bytes : play-services-tasks.properties
05.558 I: [MERGE] Zip align ...
05.639 I: [MERGE] Saved to: out.apk
05.640 I: [MERGE] Done

└─$ adb install out.apk
Performing Streamed Install
adb: failed to install out.apk: 
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl808427888.tmp/base.apk: 
Failed to collect certificates from /data/app/vmdl808427888.tmp/base.apk: Attempt to get length of null array]
```

**Comment by raoshaab** [comment]
*Sign the apk , will solve this*
Can you automate the signing process just after the merge ?

**Comment by REAndroid** [comment]
The main objective of this project is to promote and provide application example of [ARSCLib](https://github.com/REAndroid/ARSCLib) but survey likes this project than [ARSCLib](https://github.com/REAndroid/ARSCLib) :) .

Let see too many people request such feature :)

**Comment by Quicker666** [comment]
Does manifest protect auto implement after execute res protect with the new update ? @REAndroid

**Comment by REAndroid** [comment]
> Does manifest protect auto implement after execute res protect with the new update ? @REAndroid

Yes planning to change to user optional from CLI like ``` -protect-manifest ```

**Comment by Un1Gfn** [comment]
snippet

```
m() { (
 set -eu
 Z="$1"
 D="$(mktemp -d)"
 unzip -d "$D" "$Z"
 apkeditor m -i "$D" -o merge.apk
 uber-apk-signer -a merge.apk
) }
```

run

```
m com.x.y.zip
```

then install the generated ``merge-aligned-debugSigned.apk``

[uber-apk-signer](https://github.com/patrickfav/uber-apk-signer)
