### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.reandroid.arsc.chunk.TableBlock.listPackages()" because "tableBlock" is null

### ISSUE THREAD

**Issue by VD171** [REAndroid/APKEditor#82]
Got an error on v1.3.2:
> 00.014 I: [DECOMPILE] Loading ...
> 00.036 I: [DECOMPILE] Decompiling to xml ...
> 00.039 I: [DECOMPILE] [SANITIZE]: Sanitizing paths ...
> 00.040 I: [DECOMPILE] Validating resource names ...
> Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.reandroid.arsc.chunk.TableBlock.listPackages()" because "tableBlock" is null
>     at com.reandroid.identifiers.TableIdentifier.load(TableIdentifier.java:38)
>     at com.reandroid.apk.ApkModuleDecoder.validateResourceNames(ApkModuleDecoder.java:177)
>     at com.reandroid.apk.ApkModuleXmlDecoder.initialize(ApkModuleXmlDecoder.java:53)
>     at com.reandroid.apk.ApkModuleDecoder.decode(ApkModuleDecoder.java:45)
>     at com.reandroid.apkeditor.decompile.Decompiler.run(Decompiler.java:62)
>     at com.reandroid.apkeditor.decompile.Decompiler.execute(Decompiler.java:127)
>     at com.reandroid.apkeditor.Main.execute(Main.java:81)
>     at com.reandroid.apkeditor.Main.execute(Main.java:64)
>     at com.reandroid.apkeditor.Main.main(Main.java:36)

The error does NOT appear on v1.2.1 but appear on v1.2.2 and all other up versions.

**Comment by REAndroid** [comment]
Check the latest [release](https://github.com/REAndroid/APKEditor/releases/tag/V1.3.3)

**Comment by REAndroid** [comment]
@VD171 
V1.3.3 canceled and [updated](https://github.com/REAndroid/APKEditor/releases/tag/V1.3.4)
