### ISSUE TITLE
Can't add network security configuration

### ISSUE THREAD

**Issue by secureITmania** [REAndroid/APKEditor#92]
**Issue Description**
I tried to add a custom network security configuration by adding a "network_security_config.xml" file in the XML folder and defining the "android:networkSecurityConfig=@xml/network_security_config" attribute in the AndroidManifest.xml. However, I encountered an error during the build.
```
Local resource not defined: @xml/network_security_config, for path: res/xml/network_security_config.xml
```

![image](https://github.com/REAndroid/APKEditor/assets/67820809/7c4bed88-9fde-490e-849a-b4d495640344)

Please help me resolve the issue.

**Comment by REAndroid** [comment]
Did you declare it on public.xml ?

**Comment by secureITmania** [comment]
Thank you. I have declared the path in the public.xml file.
