### ISSUE TITLE
The resource id in the framework is lost

### ISSUE THREAD

**Issue by Zenlua** [REAndroid/APKEditor#95]
Android 14

The problem is that when decoding the apk the id is still fully visible, but when compressing it, the id frame is lost

I used a framework but it didn't work 
 `-framework android.apk`

After decoding

![Screenshot_2024-04-04-01-01-10-954_bin mt plus](https://github.com/REAndroid/APKEditor/assets/143571950/50d4be7b-185d-49d9-b55a-c5ecde0e711e)

Comparison on the left is the original apk, on the right is after compressing the apk

![Screenshot_2024-04-04-00-20-56-157_bin mt plus](https://github.com/REAndroid/APKEditor/assets/143571950/131d5892-7032-43ec-ba63-45a98a6c9900)

File apk: 
[framework-ext-res.zip](https://github.com/REAndroid/APKEditor/files/14856595/framework-ext-res.zip)

**Comment by REAndroid** [comment]
Fixed with [1.3.7](https://github.com/REAndroid/APKEditor/releases/tag/V1.3.7), you can re-open this issue if not fully resolved
